name: aurcade

services:
  # anubis:
  #   image: ghcr.io/techarohq/anubis:v1.27.0
  #   container_name: anubis
  #   restart: unless-stopped
  #   depends_on:
  #     - aurcade
  #   environment:
  #     BIND: ":8080"
  #     TARGET: "http://aurcade:80"
  #     POLICY_FNAME: "/data/cfg/botPolicy.yaml"
  #     # REDIRECT_DOMAINS: "aurcade.sekor.eu.org,http://localhost:8080,http://127.0.0.1:8080"
  #     USE_REMOTE_ADDRESS: "true"
  #   healthcheck:
  #     test: ["CMD", "anubis", "--healthcheck"]
  #     interval: 5s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 500ms
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./botPolicy.yaml:/data/cfg/botPolicy.yaml:ro

  aurcade:
    image: ghcr.io/skorotkiewicz/aurcade
    container_name: aurcade
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    depends_on:
      ergo:
        condition: service_started
    expose:
      - "9000"
    ports:
      - "8080:80"
      - "2222:22"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1/cgit.css"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - ./config.toml:/etc/aurcade/config.toml:ro
      - ./irc.toml:/etc/aurcade/irc.toml:ro
      - ./xmpp.toml:/etc/aurcade/xmpp.toml:ro
      - ./soju.toml:/etc/aurcade/soju.toml:ro
      - ./keys:/etc/aurcade/keys:ro
      - ./tls:/etc/aurcade/tls
      - ./repositories:/var/lib/aurcade
      - ./ssh_host_keys:/etc/ssh/host_keys
      - service_config:/etc/aurcade/services

  ergo:
    image: aurcade-ergo
    container_name: ergo
    build:
      context: .
      dockerfile: docker/Ergo.Dockerfile
    restart: unless-stopped
    ports:
      - "6697:6697"
    volumes:
      - ./config.toml:/etc/aurcade/config.toml:ro
      - ./tls:/etc/aurcade/tls:ro
      - service_config:/etc/aurcade/services:ro
      - ergo_data:/var/lib/ergo

  prosody:
    image: aurcade-prosody
    container_name: prosody
    build:
      context: .
      dockerfile: docker/Prosody.Dockerfile
    restart: unless-stopped
    ports:
      - "5222:5222"
      - "5269:5269"
    volumes:
      - ./tls:/etc/aurcade/tls:ro
      - service_config:/etc/aurcade/services:ro
      - prosody_data:/var/lib/prosody

  soju:
    image: aurcade-soju
    container_name: soju
    build:
      context: .
      dockerfile: docker/Soju.Dockerfile
    restart: unless-stopped
    depends_on:
      ergo:
        condition: service_started
    ports:
      - "6698:6698"
    volumes:
      - service_config:/etc/aurcade/services:ro
      - soju_data:/soju-data

volumes:
  ergo_data:
  prosody_data:
  soju_data:
  service_config:
