services:
  aur-repos:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
      - "2222:22"
    volumes:
      - ./config.toml:/etc/aur-repos/config.toml:ro
      - ./repositories:/var/lib/aur-repos
      - ./ssh_host_keys:/etc/ssh/host_keys

# volumes:
#   repositories:
#   ssh_host_keys:
