server.modules = ( "mod_cgi", "mod_redirect" )
server.document-root = "/usr/share/webapps/cgit"
server.port = 80
server.bind = "0.0.0.0"
server.username = "lighttpd"
server.groupname = "lighttpd"
index-file.names = ( "cgit.cgi" )
cgi.assign = ( ".cgi" => "" )
cgi.fix-pathinfo = "enable"
url.redirect = ( "^/$" => "/cgit.cgi/" )
