protocols = imap lmtp sieve
listen = *
base_dir = /run/dovecot
state_dir = /var/lib/dovecot
mail_home = /var/lib/dovecot/users/%u
mail_location = maildir:~/Maildir
mail_uid = vmail
mail_gid = vmail
first_valid_uid = 5000
last_valid_uid = 5000
auth_mechanisms = plain login
auth_username_format = %Lu
disable_plaintext_auth = yes
ssl = required
ssl_cert = </etc/aurcade/services/maddy-fullchain.pem
ssl_key = </etc/aurcade/services/maddy-privkey.pem

passdb {
  driver = passwd-file
  args = scheme=ARGON2ID username_format=%u /etc/aurcade/services/dovecot-users
}
userdb {
  driver = passwd-file
  args = username_format=%u /etc/aurcade/services/dovecot-users
}

namespace inbox {
  inbox = yes
  separator = /
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }
}

service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}
service lmtp {
  inet_listener lmtp {
    address = *
    port = 24
  }
}
service managesieve-login {
  inet_listener sieve {
    address = *
    port = 4190
  }
}

protocol lmtp {
  mail_plugins = sieve
  postmaster_address = postmaster@localhost
}
protocol sieve {
  managesieve_max_line_length = 65536
}
plugin {
  sieve = file:~/sieve;active=~/.dovecot.sieve
}

log_path = /dev/stderr
info_log_path = /dev/stderr
