state_dir /tmp/maddy-state
tls off
auth.external migration_auth {
    helper /bin/false
}
storage.imapsql local_mailboxes {
    driver sqlite3
    dsn imapsql.db
}
imap tcp://127.0.0.1:19993 {
    auth &migration_auth
    storage &local_mailboxes
}
