server.modules = ( "mod_cgi", "mod_rewrite", "mod_setenv" )
server.document-root = "/usr/share/webapps/cgit"
server.port = 80
server.bind = "0.0.0.0"
server.username = "lighttpd"
server.groupname = "lighttpd"
index-file.names = ( "cgit.cgi" )
cgi.assign = ( ".cgi" => "" )
setenv.add-environment = ( "CGIT_CONFIG" => "/var/lib/aurcade/cgitrc" )
$HTTP["url"] !~ "^/([A-Za-z0-9._-]+[.](css|gif|jpe?g|png|svg|webp)|cgit[.]cgi|favicon[.]ico|robots[.]txt)(/|$)" {
    url.rewrite-once = ( "^/(.*)$" => "/cgit.cgi/$1" )
}
