server.modules = ( "mod_alias", "mod_cgi", "mod_expire", "mod_rewrite", "mod_setenv", "mod_wstunnel" )
server.document-root = "/usr/share/webapps/cgit"
server.port = 80
server.bind = "0.0.0.0"
server.username = "lighttpd"
server.groupname = "lighttpd"
index-file.names = ( "cgit.cgi" )
cgi.assign = ( ".cgi" => "" )
alias.url = ( "/chat/" => "/usr/share/webapps/gamja/" )
wstunnel.server = ( "/webirc" => (( "host" => "ergo", "port" => "8067" )) )
wstunnel.frame-type = "text"
setenv.add-environment = (
    "CGIT_CONFIG" => "/var/lib/aurcade/cgitrc",
    "GNUPGHOME" => "/etc/aurcade/signing/gnupg",
    "GIT_CONFIG_COUNT" => "3",
    "GIT_CONFIG_KEY_0" => "gpg.ssh.allowedSignersFile",
    "GIT_CONFIG_VALUE_0" => "/etc/aurcade/signing/allowed_signers",
    "GIT_CONFIG_KEY_1" => "gpg.openpgp.program",
    "GIT_CONFIG_VALUE_1" => "/usr/bin/gpg",
    "GIT_CONFIG_KEY_2" => "gpg.ssh.program",
    "GIT_CONFIG_VALUE_2" => "/usr/bin/ssh-keygen"
)
$HTTP["url"] =~ "^/chat/?$" {
    url.rewrite-once = ( "^/chat/?$" => "/chat/index.html" )
}
$HTTP["url"] =~ "^/chat/" {
    expire.url = ( "" => "access plus 1 hours" )
}
$HTTP["url"] =~ "^/([A-Za-z0-9._-]+[.](css|gif|jpe?g|js|png|svg|webp)|favicon[.]ico|robots[.]txt)$" {
    expire.url = ( "" => "access plus 1 hours" )
}
$HTTP["url"] !~ "^/(chat|webirc)(/|$)|^/([A-Za-z0-9._-]+[.](css|gif|jpe?g|js|png|svg|webp)|cgit[.]cgi|favicon[.]ico|robots[.]txt)(/|$)" {
    url.rewrite-once = ( "^/(.*)$" => "/cgit.cgi/$1" )
}
