name: Create and publish a Docker image

on:
  push:
    tags: ['v*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./docker/aurcade/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Extract metadata for Maddy
        id: meta-maddy
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-maddy

      - name: Build and push Maddy image
        id: push-maddy
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./docker/maddy/Dockerfile
          push: true
          tags: ${{ steps.meta-maddy.outputs.tags }}
          labels: ${{ steps.meta-maddy.outputs.labels }}

      - name: Generate Maddy artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-maddy
          subject-digest: ${{ steps.push-maddy.outputs.digest }}
          push-to-registry: true

      - name: Extract metadata for SnappyMail
        id: meta-snappymail
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-snappymail

      - name: Build and push SnappyMail image
        id: push-snappymail
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./docker/snappymail/Dockerfile
          push: true
          tags: ${{ steps.meta-snappymail.outputs.tags }}
          labels: ${{ steps.meta-snappymail.outputs.labels }}

      - name: Generate SnappyMail artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-snappymail
          subject-digest: ${{ steps.push-snappymail.outputs.digest }}
          push-to-registry: true

      - name: Extract metadata for Ergo
        id: meta-ergo
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ergo

      - name: Build and push Ergo image
        id: push-ergo
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./docker/ergo/Dockerfile
          push: true
          tags: ${{ steps.meta-ergo.outputs.tags }}
          labels: ${{ steps.meta-ergo.outputs.labels }}

      - name: Generate Ergo artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ergo
          subject-digest: ${{ steps.push-ergo.outputs.digest }}
          push-to-registry: true

      - name: Extract metadata for Prosody
        id: meta-prosody
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-prosody

      - name: Build and push Prosody image
        id: push-prosody
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./docker/prosody/Dockerfile
          push: true
          tags: ${{ steps.meta-prosody.outputs.tags }}
          labels: ${{ steps.meta-prosody.outputs.labels }}

      - name: Generate Prosody artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-prosody
          subject-digest: ${{ steps.push-prosody.outputs.digest }}
          push-to-registry: true

      - name: Extract metadata for Soju
        id: meta-soju
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-soju

      - name: Build and push Soju image
        id: push-soju
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./docker/soju/Dockerfile
          push: true
          tags: ${{ steps.meta-soju.outputs.tags }}
          labels: ${{ steps.meta-soju.outputs.labels }}

      - name: Generate Soju artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-soju
          subject-digest: ${{ steps.push-soju.outputs.digest }}
          push-to-registry: true
